### PR TITLE
Trackswitch image caching fix

### PR DESCRIPTION
**Pull request by sebastianrosenzweig**
As discussed in issue #2

### CODE REVIEW

**Review by jpauwels — CHANGES_REQUESTED** [review]
Thanks a lot for this PR! I have a small style issue, however. I'd add the random id as
```
<img src="{}#{}" data-style="width: {}px;" class="seekable"{}/>'''.format(seekable_image_path, unique_id, image_width, ...
```
instead of nesting string interpolation (in two different styles). Could you change this line and squash your commits such that the final PR is a one-liner single commit? You've also changed the default globalsolo parameter, while I'd like to keep it in line with the trackswitch.js defaults.

If that's too much of a hassle, don't worry about it. I can rewrite your PR in a couple of days, while still giving you full credit.

**Review by sebastianrosenzweig — COMMENTED** [review]
Thanks, that makes sense!
For me, `globalsolo=True` causes playback problems when using multiple players in a notebook, but one can set this manually to `False` anyways...

**Comment by sebastianrosenzweig** [comment]
Since this is my first pull request ever I struggled a bit, but now, I think, I managed to incorporate your changes...^^:D

**Comment by jpauwels** [comment]
Great, that looks perfect indeed. Congratulations on your first PR , may many more follow.

I ended up doing some work myself and ended up applying your patch locally, so don't worry if it doesn't look merged in the GitHub interface. I've split off the code to use specifically for Jupyter Notebook in a separate file, so you should now do `import pywebaudioplayer.notebook as pwa` instead of `import pywebaudioplayer as pwa`, but otherwise the rest remains the same. Have a look at the updated `example-notebook.ipynb` if you like.

For now there's a lot of duplicated code due in the `notebook.py` file, which I'll resolve over time, but this way I can experiment a bit more without breaking everything. I've also released the reorganised module with your patch as version 0.0.5 on PyPI, so you can `pip install [-U]` the latest version.

**Pull request closed without merging**
